Added test for title extraction.

diff --git a/dvd-ripper/dvd-ripper b/dvd-ripper/dvd-ripper
--- a/dvd-ripper/dvd-ripper
+++ b/dvd-ripper/dvd-ripper
@@ -27,12 +27,14 @@ getInfo()
 #Function to strip the extraneous text from the TITLE variable
 stripTitle()
 {
-	#echo "Entire string:"
-	#echo "$TITLE"
-	#echo "Stripped:"
  	TITLE="${TITLE#DVD-Video\ information\ of\ the\ DVD\ with\ title\ \"}"
 	TITLE="${TITLE%\"}"
-	echo "$TITLE"
+	#echo "$TITLE"		#For debug
+	if [ ! -e $TITLE ]
+	then
+		echo "Unable to rip title!"
+		exit 1
+	fi
 }
 
 #Function to rip the disc now that we have a title
